---
name: Audit dependencies
on:
  pull_request:
    paths:
      - .github/workflows/cargo-audit.yml
      - Cargo.toml
      - Cargo.lock
  schedule:
    # At 06:20 UTC every day. Will create an issue if a CVE is found.
    - cron: '20 6 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/audit@5c5da92c0334eb692d0735bb94f086fd83e59572 # v1.2.2
        name: Audit Rust Dependencies
        with:
          denyWarnings: true
          # Ignored audit issues. This list should be kept short, and effort should be
          # put into removing items from the list.
          ignore:
