---
name: Rust formatting
on:
  pull_request:
    paths:
      - .github/workflows/formatting.yml
      - '**/*.rs'
  workflow_dispatch:
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # master at the time of writing this
        with:
          toolchain: stable
          components: rustfmt

      - name: Check formatting
        run: |
          rustfmt --version
          cargo fmt -- --check
